#!/bin/bash

function printMsg () {
    qut='"'
    echo "echo ${qut}${1}${qut}"
}

function listProfiles () {
    space=' '
    while read line; do                
        if [[ $line == "["* ]]; then 
            line=${line//[][,.!]}            
            printf -v var "%q" ${line}            
            printMsg "- ${var}"
        fi;
    done < ~/.aws/credentials;
}
 
function switchProfile () {
    access_key="$(aws configure get aws_access_key_id --profile $1 2>/dev/null)"
    secrete_key="$(aws configure get aws_secret_access_key --profile $1 2>/dev/null)"
    region="$(aws configure get region --profile $1 2>/dev/null)"
    global_region=${AWS_GLOBAL_REGION:-$AWS_DEFAULT_REGION}
    global_region=${global_region:-$AWS_REGION}
    global_region=${global_region:-us-east-1}
    region=${region:-$global_region}
    
    if [ -z $access_key ] || [ -z $secrete_key ]; then
        printMsg "Profile ($1) does not exist or incomplete"
        exit 1
    else
        echo "export AWS_PROFILE=$1"
        echo "export AWS_DEFAULT_PROFILE=$1"
        echo "export AWS_ACCESS_KEY_ID=$access_key"
        echo "export AWS_SECRET_ACCESS_KEY=$secrete_key"
        echo "export AWS_DEFAULT_REGION=$region"
        echo "export AWS_REGION=$region"
        echo "export AWS_GLOBAL_REGION=$global_region"
   
        printMsg "\nCurrent profile: $1 ($region)\n"
    fi
}

function initProfile () {
    profile=${AWS_DEFAULT_PROFILE:-$AWS_PROFILE} 

    if [ $profile ]; then    
        switchProfile $profile
    else
        printMsg 'No default profile found. To set a profile, run: awsenv use [profile_name]' 
    fi  
}

if [ $# -eq 0 ]; then
    initProfile
elif [ $1 = "ls" -a $# -eq 1 ]; then
    listProfiles
elif [ $1 = "use" -a $# -eq 2 ]; then
    switchProfile $2
else
    printMsg "\nUsage: awsenv [use profile_name] | [ls]\n"
fi

exit 0